// Auto-generated by scripts/write-build-sha.mjs before dev/build/test --
// do not hand-edit. The checked-in value is a placeholder; every real
// dev/build/test run overwrites it with the actual current commit.
export const BUILD_SHA: string | null = null;
