import Link from "next/link";
import { PlaneTakeoff } from "lucide-react";
import { buttonVariants } from "@/components/ui/button";
import { ListenButton } from "@/components/listen-button";
import { StudyResourceLink } from "@/components/study-resource-link";
import { TrainingItemChecklist } from "@/components/training-item-checklist";
import { PageTitle, Screen, Section, SecondaryButton, VectorMark } from "@/components/student/ui";
import { getRepository } from "@/lib/data";
import { getViewer } from "@/lib/viewer";
import { computeNextLessonBrief } from "@/lib/training-memory";
import { instructorAttributionLabel } from "@/lib/instructor-attribution";
import { assessTranscriptAdequacy } from "@/lib/transcript-adequacy";
import { deriveKeepBuilding, deriveNextFlightFocus, type TaskRating } from "@/lib/next-flight-focus";
import { LocalDateTime } from "@/components/local-date-time";

export const dynamic = "force-dynamic";

/**
 * A 30-second pre-flight briefing, not a dashboard -- deliberately excludes
 * the instructor-continuity moment (see components/debrief/student-
 * debrief-v2.tsx's recurring-theme Panel), which lives on the debrief a
 * theme was actually found on rather than being repeated here. See
 * lib/training-memory.ts's computeNextLessonBrief for most of what's used
 * below; this page additionally reads the last flight's own assessment
 * ratings (real, human-entered, not something the brief computation
 * exposes) and re-checks the last debrief's transcript against
 * lib/transcript-adequacy.ts before trusting any of its free-text AI
 * fields -- see the "Focus on"/"From your last flight" comments below for
 * why.
 */
export default async function NextLessonPage() {
  const repo = getRepository();
  const viewer = await getViewer();
  const brief = await computeNextLessonBrief(repo, viewer.user.id);

  if (!brief.lastFlight) {
    return (
      <Screen>
        <div className="flex flex-col items-center gap-4 py-16 text-center">
          <PlaneTakeoff className="size-10 text-foreground-faint" aria-hidden />
          <h1 className="text-[28px] font-semibold text-foreground">Next Flight</h1>
          <p className="text-foreground-soft">Your Next Flight brief will appear after your first completed debrief.</p>
          <Link href="/dashboard" className={buttonVariants()}>
            Go to flights
          </Link>
        </div>
      </Screen>
    );
  }

  const studyReferences = brief.lastDebrief?.structuredResult.studyReferences ?? [];
  const ttsEnabled = Boolean(process.env.DEEPGRAM_API_KEY);

  // A solo pilot has no instructor, and saying "your instructor wanted you to
  // work on" to someone the product told "no CFI needed" contradicts the
  // page they signed up from. instructorAttributionLabel() takes the raw
  // instructor record (not just its resolved name) so it can tell "no
  // instructor at all" apart from "instructor with an unresolvable name" --
  // only the former should ever produce a null here.
  const cfi = instructorAttributionLabel(brief.lastInstructor);

  // The last debrief's own free-text fields (wentWell, nextLessonFocus) were
  // generated by an AI model with no enforcement mechanism beyond the
  // prompt's own "don't invent" instructions -- see lib/ai/prompt.ts and
  // lib/transcript-adequacy.ts's own doc comment for the real Staging
  // incident that motivated this recheck. A debrief analyzed before that
  // gate existed can still be sitting in the database with fabricated
  // content in exactly these fields, so they're re-validated against the
  // gate at render time rather than trusted just because they're persisted.
  // Ratings (student/instructor) and TrainingSignal-derived recurring
  // themes are NOT gated by this -- they're human-entered or deterministic,
  // not free AI prose, so an old thin debrief can't have fabricated them.
  const lastDebriefTrusted = brief.lastDebrief ? assessTranscriptAdequacy(brief.lastDebrief.transcript).adequate : false;

  const [studentAssessment, instructorAssessment, lastFlightTasks] = await Promise.all([
    repo.getAssessment(brief.lastFlight.id, "student"),
    brief.lastInstructor ? repo.getAssessment(brief.lastFlight.id, "instructor") : Promise.resolve(null),
    repo.listFlightTasks(brief.lastFlight.id),
  ]);
  const taskLabels = new Map(lastFlightTasks.map((t) => [t.id, t.label]));

  async function ratingsFor(assessment: Awaited<ReturnType<typeof repo.getAssessment>>): Promise<TaskRating[]> {
    if (!assessment || assessment.status !== "submitted") return [];
    const rows = await repo.listAssessmentRatings(assessment.id);
    return rows
      .map((r) => ({ label: taskLabels.get(r.flightTaskId), performanceLevel: r.performanceLevel }))
      .filter((r): r is TaskRating => Boolean(r.label));
  }
  const [studentRatings, instructorRatings] = await Promise.all([
    ratingsFor(studentAssessment),
    ratingsFor(instructorAssessment),
  ]);

  const focus = deriveNextFlightFocus({
    recurringTheme: brief.recurringThemes[0] ?? null,
    instructorRatings,
    studentRatings,
    instructorName: cfi,
    aiFocusAreas: brief.focusAreas,
    aiContentTrusted: lastDebriefTrusted,
  });
  const keepBuilding = deriveKeepBuilding(instructorRatings, studentRatings, cfi, focus?.headline ?? null).slice(0, 3);
  const trustedWentWell = lastDebriefTrusted ? brief.lastWentWell : [];

  const viewedUrls = studyReferences.length > 0 ? new Set(await repo.listViewedStudyResourceUrls(viewer.user.id)) : new Set<string>();
  // Same fields the CFI's per-student page shows -- if every one of them is
  // empty, the page below would otherwise just be a blank stretch under the
  // header with no explanation of why there's nothing to show.
  const hasAnyContent =
    focus !== null ||
    keepBuilding.length > 0 ||
    trustedWentWell.length > 0 ||
    brief.beforeFlightItems.length > 0 ||
    studyReferences.length > 0 ||
    Boolean(brief.suggestedQuestion);

  // Marks the "Prepare for your next flight" Guide step (lib/guide.ts).
  if (!viewer.user.guideProgress?.nextFlight) {
    void repo.markGuideStepViewed(viewer.user.id, "nextFlight").catch(() => {});
  }

  return (
    <Screen>
      <PageTitle kicker={cfi ? `Based on your debrief with ${cfi}` : "Based on your latest debrief"}>Next Flight</PageTitle>
      {ttsEnabled ? <ListenButton baseSrc="/api/next-lesson/audio" label="Listen to your brief" /> : null}

      {brief.upcomingReservation ? (
        <Section title="When">
          <p className="text-[17px] text-foreground">
            <LocalDateTime
              iso={brief.upcomingReservation.scheduledStart}
              options={{ weekday: "long", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }}
            />
          </p>
        </Section>
      ) : null}

      {!hasAnyContent ? (
        <p className="rounded-2xl border border-hairline bg-surface px-5 py-6 text-center text-[15px] text-foreground-soft">
          Not enough was captured from your last debrief to build a next-flight plan yet -- rate your flights and
          it&rsquo;ll fill in here.
        </p>
      ) : null}

      {focus ? (
        <Section title="Focus on">
          <div className="flex flex-col gap-2">
            <p className="text-[22px] font-semibold leading-snug text-foreground">{focus.headline}</p>
            {focus.evidence ? <p className="text-[15px] leading-relaxed text-foreground-soft">{focus.evidence}</p> : null}
          </div>
        </Section>
      ) : null}

      {keepBuilding.length > 0 ? (
        <Section title="Keep building">
          <ul className="flex flex-col gap-2">
            {keepBuilding.map((item, i) => (
              <li key={i} className="flex items-start gap-2 text-[15px] leading-relaxed text-foreground-soft">
                <span className="mt-2 size-1.5 shrink-0 rounded-full bg-brand" />
                {item}
              </li>
            ))}
          </ul>
        </Section>
      ) : null}

      {brief.beforeFlightTrainingItems.length > 0 || (focus?.kind === "recurring_theme" && focus.skill) ? (
        <Section title="Before you fly">
          <div className="flex flex-col gap-3">
            {brief.beforeFlightTrainingItems.length > 0 ? (
              <>
                <p className="text-[14px] text-foreground-faint">Check off what you&rsquo;ve reviewed -- this is for you, nobody else sees it.</p>
                <TrainingItemChecklist items={brief.beforeFlightTrainingItems} />
              </>
            ) : null}
            {/* Only linked when the focus itself came from a recurring theme --
                that's the one tier with a real catalog skill code behind it, so
                /progress/[skill] is guaranteed to have real progression data to
                show rather than 404ing. A rating or an AI focus-area headline is
                free text with no such guarantee. */}
            {focus?.kind === "recurring_theme" && focus.skill ? (
              <Link href={`/progress/${focus.skill}`} className="text-[15px] font-medium text-brand">
                Review {focus.headline.toLowerCase()}
              </Link>
            ) : null}
          </div>
        </Section>
      ) : null}

      {studyReferences.length > 0 ? (
        <Section title="Recommended study">
          <ul className="flex flex-col gap-4">
            {studyReferences.map((ref, i) => (
              <li key={i} className="flex flex-col gap-0.5">
                <span className="text-[13px] font-semibold uppercase tracking-[0.06em] text-foreground-faint">{ref.topic}</span>
                {ref.url ? (
                  <StudyResourceLink url={ref.url} label={ref.source} initiallyViewed={viewedUrls.has(ref.url)} />
                ) : (
                  <span className="text-[15px] text-foreground-soft">{ref.source}</span>
                )}
              </li>
            ))}
          </ul>
        </Section>
      ) : null}

      {trustedWentWell.length > 0 ? (
        <Section title="From your last flight">
          <ul className="flex flex-col gap-2">
            {trustedWentWell.map((item, i) => (
              <li key={i} className="flex items-start gap-2 text-[15px] leading-relaxed text-foreground-soft">
                <span className="mt-2 size-1.5 shrink-0 rounded-full bg-state-good" />
                {item}
              </li>
            ))}
          </ul>
        </Section>
      ) : null}

      {/*
       * "Vector guidance" from the Phase 3 brief, represented honestly: this
       * is brief.suggestedQuestion -- a real, deterministic template over
       * this debrief's own content (lib/training-memory.ts's
       * buildSuggestedQuestion, never LLM-generated) -- with Vector's
       * identity attached, not a live chat. A production Ask-Vector
       * endpoint (lib/ai/vector.ts's askVector) exists but its only current
       * route is deliberately unauthenticated and prototype-only (see
       * app/api/prototype/vector/route.ts); wiring a new authenticated
       * production endpoint is backend work beyond this reskin, not
       * something to fake here.
       */}
      {brief.suggestedQuestion ? (
        <Section title={cfi ? "Ask your instructor" : "Worth thinking about"} flush>
          <div className="rounded-2xl border border-hairline bg-surface px-5 py-4">
            <VectorMark subtitle="Suggested by Vector" />
            <p className="mt-3 text-[17px] text-foreground">&ldquo;{brief.suggestedQuestion}&rdquo;</p>
          </div>
        </Section>
      ) : null}

      {/* Deliberately secondary, not a primary CTA. This page is a pre-flight
          read -- the student's actual next step is to go fly, not to press
          anything here. Logging is the after-landing action, kept available
          for whoever lands and comes back to this page, but styled so it
          doesn't read as "do this now." */}
      <div className="flex flex-col items-center gap-1.5 border-t border-hairline pt-5">
        <p className="text-[15px] text-foreground-soft">Already flown it?</p>
        <div className="mt-1 flex w-full">
          <SecondaryButton href="/flights/new">Log this flight</SecondaryButton>
        </div>
      </div>
    </Screen>
  );
}
